<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.37-alpha</Version>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <AssemblyVersion></AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>DaemonMC</Title>
    <Description>Simple and lightning fast Minecraft Bedrock Edition server software</Description>
    <Copyright>TeamDeamonMC</Copyright>
    <PackageProjectUrl>https://github.com/TeamDeamonMC/DaemonMC/wiki</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TeamDeamonMC/DaemonMC</RepositoryUrl>
    <PackageTags>mcpe; bedrock-server; bedrock-dedicated-server; minecraft</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DaemonMC-fNbt" Version="1.0.0.3" />
    <PackageReference Include="MiNET.LevelDB-CobwebSMP" Version="0.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <PackageReference Include="Snappier" Version="1.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

</Project>
