namespace DaemonMC.Items.VanillaItems
{
    public class BreezeRod : Item
    {
        public BreezeRod()
        {
            Name = "minecraft:breeze_rod";
            Id = 281;
            Version = 1;
            ComponentBased = true;
            ComponentData = "CgAACgoAY29tcG9uZW50cwoPAGl0ZW1fcHJvcGVydGllcwEOAGFsbG93X29mZl9oYW5kAAEXAGNhbl9kZXN0cm95X2luX2NyZWF0aXZlAQMRAGNyZWF0aXZlX2NhdGVnb3J5BAAAAAgOAGNyZWF0aXZlX2dyb3VwAAADBgBkYW1hZ2UAAAAACBAAZW5jaGFudGFibGVfc2xvdAQAbm9uZQMRAGVuY2hhbnRhYmxlX3ZhbHVlAAAAAAEEAGZvaWwAAwsAZnJhbWVfY291bnQBAAAAAQ0AaGFuZF9lcXVpcHBlZAEBEgBoaWRkZW5faW5fY29tbWFuZHMCAQ4AbGlxdWlkX2NsaXBwZWQAAw4AbWF4X3N0YWNrX3NpemVAAAAACg4AbWluZWNyYWZ0Omljb24KCAB0ZXh0dXJlcwgHAGRlZmF1bHQKAGJyZWV6ZV9yb2QAAAUMAG1pbmluZ19zcGVlZAAAgD8BDgBzaG91bGRfZGVzcGF3bgEBDwBzdGFja2VkX2J5X2RhdGEAAw0AdXNlX2FuaW1hdGlvbgAAAAADDAB1c2VfZHVyYXRpb24AAAAAAAkJAGl0ZW1fdGFncwAAAAAAChYAbWluZWNyYWZ0OmRpc3BsYXlfbmFtZQgFAHZhbHVlFABpdGVtLmJyZWV6ZV9yb2QubmFtZQAKFwBtaW5lY3JhZnQ6aGFuZF9lcXVpcHBlZAEFAHZhbHVlAQAAAA==";
        }
    }
}